apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: twns-pvc
  labels:
    app: cassandra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  selector:
    matchLabels:
      app: cassandra
      tier: best-database
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cassandra
        tier: best-database
    spec:
      containers:
      - image: cassandra
        name: cassandra
        volumeMounts:
        - name: cassandrapvc
          mountPath: /var/lib/cassandra
      volumes:
      - name: cassandrapvc
        persistentVolumeClaim:
          claimName: twns-pvc
